import json
from pathlib import Path

AUTOGENERATED_MARKERS = (
    "This page is auto-generated from the Pydantic model schema.",
    "Diese Seite wurde automatisch aus dem Pydantic-Model generiert.",
)


def is_required(name: str, required_list: list[str] | None) -> bool:
    return bool(required_list) and name in required_list


def _escape_md_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _inline_type(prop: dict) -> str:
    if "$ref" in prop:
        return prop["$ref"].split("/")[-1]
    if "const" in prop:
        return repr(prop["const"])
    if "enum" in prop:
        values = ", ".join(repr(v) for v in prop["enum"])
        return f"enum({values})"
    if "anyOf" in prop:
        return " | ".join(_inline_type(part) for part in prop["anyOf"])
    if "oneOf" in prop:
        return " | ".join(_inline_type(part) for part in prop["oneOf"])
    if "allOf" in prop:
        return " & ".join(_inline_type(part) for part in prop["allOf"])
    if "type" in prop:
        value = prop["type"]
        if isinstance(value, list):
            return " | ".join(str(part) for part in value)
        if value == "array":
            items = prop.get("items", {})
            return f"array[{_inline_type(items)}]"
        return str(value)
    return "unknown"


def _build_markdown(schema: dict, fallback_title: str) -> str:
    title = schema.get("title", fallback_title)
    root_props = schema.get("properties", {})
    root_required = schema.get("required", [])

    md: list[str] = []
    md.append(f"# {title}\n\n")
    md.append("This page is auto-generated from the Pydantic model schema.\n\n")

    md.append("## Top-Level Fields\n\n")
    if root_props:
        md.append("| Field | Type | Required? | Description |\n")
        md.append("|---|---|---|---|\n")
        for name, prop in root_props.items():
            desc = _escape_md_cell(str(prop.get("description", "")))
            required = "yes" if is_required(name, root_required) else "no"
            md.append(
                f"| `{name}` | `{_inline_type(prop)}` | {required} | {desc} |\n"
            )
    else:
        md.append("_No top-level object fields._\n")

    defs = schema.get("$defs", {})
    object_defs = [
        (name, item) for name, item in defs.items() if item.get("type") == "object"
    ]
    if object_defs:
        md.append("\n## Types / Elements\n")
        for def_name, def_schema in object_defs:
            props = def_schema.get("properties", {})
            req = def_schema.get("required", [])

            md.append(f"\n### {def_name}\n\n")
            if not props:
                md.append("_No fields._\n")
                continue

            md.append("| Field | Type | Required? | Description |\n")
            md.append("|---|---|---|---|\n")
            for prop_name, prop_schema in props.items():
                desc = _escape_md_cell(str(prop_schema.get("description", "")))
                required = "yes" if is_required(prop_name, req) else "no"
                md.append(
                    f"| `{prop_name}` | `{_inline_type(prop_schema)}` | {required} | {desc} |\n"
                )

    return "".join(md)


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    schema_dir = repo_root / "schemas"
    docs_dir = repo_root / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    expected_docs: set[str] = set()

    for schema_path in sorted(schema_dir.glob("*.schema.json")):
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
        doc_name = schema_path.name.replace(".schema.json", ".md")
        expected_docs.add(doc_name)
        doc_path = docs_dir / doc_name
        fallback_title = schema_path.name.replace(".schema.json", "")

        markdown = _build_markdown(schema, fallback_title=fallback_title)
        doc_path.write_text(markdown, encoding="utf-8")
        print(f"OK: {doc_path.relative_to(repo_root)}")

    for doc_path in sorted(docs_dir.glob("*.md")):
        if doc_path.name in expected_docs:
            continue
        content = doc_path.read_text(encoding="utf-8")
        if any(marker in content for marker in AUTOGENERATED_MARKERS):
            doc_path.unlink()
            print(f"REMOVED: {doc_path.relative_to(repo_root)}")


if __name__ == "__main__":
    main()
