#!/usr/bin/env python3
"""Generate C# DTOs from the backend OpenAPI document."""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

DEFAULT_OPENAPI_URL = "http://127.0.0.1:8000/openapi.json"
DEFAULT_NAMESPACE = "Vivian.Backend.Dtos"
SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_OUTPUT_DIR = SCRIPT_DIR / "dtos"
OPENAPI_SNAPSHOT_PATH = SCRIPT_DIR / "openapi" / "openapi.json"
GENERATOR_MARKER = "// Generated by backend/Scripts/generate_dtos.py"


@dataclass(frozen=True)
class ResolvedType:
    name: str
    nullable: bool


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fetch OpenAPI JSON and generate C# DTO classes/enums.",
    )
    parser.add_argument(
        "--openapi-url",
        default=DEFAULT_OPENAPI_URL,
        help=f"OpenAPI endpoint URL (default: {DEFAULT_OPENAPI_URL})",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Output directory for DTO files (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--namespace",
        default=DEFAULT_NAMESPACE,
        help=f"C# namespace for generated types (default: {DEFAULT_NAMESPACE})",
    )
    parser.add_argument(
        "--timeout-seconds",
        type=float,
        default=10.0,
        help="HTTP timeout in seconds (default: 10)",
    )
    parser.add_argument(
        "--retries",
        type=int,
        default=6,
        help="How many fetch attempts to make (default: 6)",
    )
    parser.add_argument(
        "--retry-delay-seconds",
        type=float,
        default=2.0,
        help="Delay between retries in seconds (default: 2)",
    )
    return parser.parse_args()


def fetch_openapi_json(
    *,
    url: str,
    timeout_seconds: float,
    retries: int,
    retry_delay_seconds: float,
) -> dict[str, Any]:
    retries = max(1, retries)
    timeout_seconds = max(0.5, timeout_seconds)
    retry_delay_seconds = max(0.0, retry_delay_seconds)

    last_error: Exception | None = None
    for attempt in range(1, retries + 1):
        try:
            req = Request(url, headers={"Accept": "application/json"})
            with urlopen(req, timeout=timeout_seconds) as response:
                status_code = getattr(response, "status", None) or response.getcode()
                if status_code != 200:
                    raise RuntimeError(f"Unexpected HTTP {status_code} from {url}")
                body = response.read()
            payload = json.loads(body.decode("utf-8"))
            if not isinstance(payload, dict):
                raise RuntimeError("OpenAPI payload is not a JSON object.")
            return payload
        except (HTTPError, URLError, TimeoutError, json.JSONDecodeError, RuntimeError) as exc:
            last_error = exc
            if attempt < retries:
                print(
                    f"[warn] fetch attempt {attempt}/{retries} failed: {exc}",
                    file=sys.stderr,
                )
                if retry_delay_seconds > 0:
                    time.sleep(retry_delay_seconds)
                continue
            break

    raise RuntimeError(
        f"Failed to fetch OpenAPI JSON from {url} after {retries} attempts: {last_error}"
    )


def to_pascal_case(name: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", name)
    converted = "".join(part[:1].upper() + part[1:] for part in parts if part)
    if not converted:
        converted = "Field"
    if converted[0].isdigit():
        converted = f"_{converted}"
    return converted


def sanitize_identifier(name: str, fallback: str) -> str:
    candidate = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not candidate:
        candidate = fallback
    if candidate[0].isdigit():
        candidate = f"_{candidate}"
    return candidate


def parse_ref_name(ref: str) -> str:
    return ref.rsplit("/", maxsplit=1)[-1]


def indent(text: str, spaces: int = 4) -> str:
    pad = " " * spaces
    return "\n".join(f"{pad}{line}" if line else "" for line in text.splitlines())


def is_schema_enum(schema: dict[str, Any]) -> bool:
    enum_values = schema.get("enum")
    return isinstance(enum_values, list) and len(enum_values) > 0


def is_schema_object(schema: dict[str, Any]) -> bool:
    if schema.get("type") == "object":
        return True
    if isinstance(schema.get("properties"), dict):
        return True
    return False


def is_schema_list_alias(schema: dict[str, Any]) -> bool:
    return schema.get("type") == "array"


def is_schema_dict_alias(schema: dict[str, Any]) -> bool:
    return (
        schema.get("type") == "object"
        and not schema.get("properties")
        and "additionalProperties" in schema
    )


class CSharpGenerator:
    def __init__(self, schemas: dict[str, Any], namespace: str) -> None:
        self.schemas = schemas
        self.namespace = namespace
        self.enum_names = {name for name, schema in schemas.items() if is_schema_enum(schema)}

    def resolve_schema_type(self, schema: dict[str, Any]) -> ResolvedType:
        if "$ref" in schema:
            return ResolvedType(parse_ref_name(schema["$ref"]), False)

        combinator = schema.get("anyOf") or schema.get("oneOf")
        if isinstance(combinator, list) and combinator:
            non_null = [entry for entry in combinator if entry.get("type") != "null"]
            nullable = len(non_null) != len(combinator)
            if len(non_null) == 1:
                resolved = self.resolve_schema_type(non_null[0])
                return ResolvedType(resolved.name, resolved.nullable or nullable)
            return ResolvedType("JToken", nullable)

        all_of = schema.get("allOf")
        if isinstance(all_of, list) and all_of:
            if len(all_of) == 1:
                return self.resolve_schema_type(all_of[0])
            return ResolvedType("JToken", False)

        schema_type = schema.get("type")
        if isinstance(schema_type, list):
            non_null = [item for item in schema_type if item != "null"]
            if len(non_null) == 1:
                resolved = self.resolve_schema_type({**schema, "type": non_null[0]})
                return ResolvedType(resolved.name, True)
            return ResolvedType("JToken", "null" in schema_type)

        if schema_type == "string":
            string_format = schema.get("format")
            if string_format == "date-time":
                return ResolvedType("DateTimeOffset", False)
            if string_format == "date":
                return ResolvedType("DateOnly", False)
            if string_format == "uuid":
                return ResolvedType("Guid", False)
            if string_format in {"byte", "binary"}:
                return ResolvedType("byte[]", False)
            return ResolvedType("string", False)
        if schema_type == "integer":
            if schema.get("format") == "int64":
                return ResolvedType("long", False)
            return ResolvedType("int", False)
        if schema_type == "number":
            if schema.get("format") == "float":
                return ResolvedType("float", False)
            if schema.get("format") == "decimal":
                return ResolvedType("decimal", False)
            return ResolvedType("double", False)
        if schema_type == "boolean":
            return ResolvedType("bool", False)
        if schema_type == "array":
            items = schema.get("items", {})
            item_type = self.resolve_schema_type(items).name
            return ResolvedType(f"List<{item_type}>", False)
        if schema_type == "object" or "additionalProperties" in schema:
            additional = schema.get("additionalProperties")
            if isinstance(additional, dict):
                value_type = self.resolve_schema_type(additional).name
                return ResolvedType(f"Dictionary<string, {value_type}>", False)
            return ResolvedType("Dictionary<string, JToken>", False)

        return ResolvedType("JToken", False)

    def apply_nullable(self, type_name: str, nullable: bool) -> str:
        if not nullable:
            return type_name
        if type_name.endswith("?"):
            return type_name
        if self.is_value_type(type_name):
            return f"{type_name}?"
        return f"{type_name}?"

    def is_value_type(self, type_name: str) -> bool:
        clean = type_name.rstrip("?")
        if clean in self.enum_names:
            return True
        return clean in {
            "bool",
            "byte",
            "short",
            "int",
            "long",
            "float",
            "double",
            "decimal",
            "Guid",
            "DateTime",
            "DateTimeOffset",
            "DateOnly",
            "TimeOnly",
        }

    def render_enum(self, name: str, schema: dict[str, Any]) -> str:
        enum_values = schema.get("enum", [])
        members: list[str] = []
        used_names: set[str] = set()

        for index, raw_value in enumerate(enum_values):
            if not isinstance(raw_value, str):
                continue
            member_name = sanitize_identifier(raw_value, fallback=f"Value{index + 1}")
            while member_name in used_names:
                member_name = f"{member_name}_{index + 1}"
            used_names.add(member_name)
            if member_name != raw_value:
                members.append(f"// \"{raw_value}\"")
            members.append(member_name + ",")

        body = "\n".join(indent(member, 4) for member in members) if members else "    // empty enum"
        return (
            "[JsonConverter(typeof(StringEnumConverter))]\n"
            f"public enum {name}\n"
            "{\n"
            f"{body}\n"
            "}\n"
        )

    def render_dict_alias(self, name: str, schema: dict[str, Any]) -> str:
        additional = schema.get("additionalProperties")
        value_type = "JToken"
        if isinstance(additional, dict):
            value_type = self.resolve_schema_type(additional).name
        return f"public class {name} : Dictionary<string, {value_type}> {{ }}\n"

    def render_list_alias(self, name: str, schema: dict[str, Any]) -> str:
        items = schema.get("items", {})
        item_type = self.resolve_schema_type(items).name
        return f"public class {name} : List<{item_type}> {{ }}\n"

    def render_class(self, name: str, schema: dict[str, Any]) -> str:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        lines: list[str] = [f"public class {name}", "{"] 

        if not isinstance(properties, dict) or not properties:
            lines.append("}")
            return "\n".join(lines) + "\n"

        for json_name, prop_schema in properties.items():
            if not isinstance(prop_schema, dict):
                prop_schema = {}
            prop_name = to_pascal_case(json_name)
            resolved = self.resolve_schema_type(prop_schema)
            nullable = resolved.nullable or (json_name not in required)
            csharp_type = self.apply_nullable(resolved.name, nullable)

            lines.append(indent(f'[JsonProperty("{json_name}")]'))
            initializer = ""
            is_reference_non_nullable = (not self.is_value_type(csharp_type)) and (not csharp_type.endswith("?"))
            if is_reference_non_nullable:
                initializer = " = default!;"
            lines.append(
                indent(
                    f"public {csharp_type} {prop_name} {{ get; set; }}{initializer}"
                )
            )
            lines.append("")

        if lines[-1] == "":
            lines.pop()
        lines.append("}")
        return "\n".join(lines) + "\n"

    def file_prefix(self) -> str:
        return "\n".join(
            [
                "// <auto-generated />",
                GENERATOR_MARKER,
                "",
                "using System;",
                "using System.Collections.Generic;",
                "using Newtonsoft.Json;",
                "using Newtonsoft.Json.Converters;",
                "using Newtonsoft.Json.Linq;",
                "",
            ]
        )

    def render_types(self) -> dict[str, str]:
        rendered: dict[str, str] = {}
        for name in sorted(self.schemas):
            schema = self.schemas[name]
            if not isinstance(schema, dict):
                continue
            body: str | None = None
            if is_schema_enum(schema):
                body = self.render_enum(name, schema).rstrip()
            elif is_schema_dict_alias(schema):
                body = self.render_dict_alias(name, schema).rstrip()
            elif is_schema_list_alias(schema):
                body = self.render_list_alias(name, schema).rstrip()
            elif is_schema_object(schema):
                body = self.render_class(name, schema).rstrip()

            if body is not None:
                rendered[name] = (
                    f"{self.file_prefix()}"
                    f"namespace {self.namespace}\n"
                    "{\n"
                    f"{indent(body, 4)}\n"
                    "}\n"
                )
        return rendered


def cleanup_generated_cs_files(output_dir: Path) -> None:
    for candidate in output_dir.glob("*.cs"):
        try:
            content = candidate.read_text(encoding="utf-8")
        except Exception:
            continue
        if GENERATOR_MARKER in content:
            candidate.unlink(missing_ok=True)


def generate_dtos(
    *,
    openapi_json: dict[str, Any],
    output_dir: Path,
    namespace: str,
) -> tuple[Path, list[Path]]:
    schemas = (
        openapi_json.get("components", {})
        .get("schemas", {})
    )
    if not isinstance(schemas, dict) or not schemas:
        raise RuntimeError("No schemas found under components.schemas in OpenAPI document.")

    output_dir.mkdir(parents=True, exist_ok=True)
    openapi_path = OPENAPI_SNAPSHOT_PATH
    openapi_path.parent.mkdir(parents=True, exist_ok=True)

    openapi_path.write_text(json.dumps(openapi_json, indent=2, ensure_ascii=False), encoding="utf-8")
    legacy_openapi_path = output_dir / "openapi.json"
    if legacy_openapi_path.resolve() != openapi_path.resolve():
        legacy_openapi_path.unlink(missing_ok=True)

    generator = CSharpGenerator(schemas=schemas, namespace=namespace)
    rendered_types = generator.render_types()
    if not rendered_types:
        raise RuntimeError("No DTO types could be generated from components.schemas.")

    cleanup_generated_cs_files(output_dir)

    written_files: list[Path] = []
    for type_name, content in rendered_types.items():
        dto_path = output_dir / f"{type_name}.cs"
        dto_path.write_text(content, encoding="utf-8")
        written_files.append(dto_path)
    return openapi_path, written_files


def main() -> int:
    args = parse_args()
    output_dir = args.output_dir.resolve()

    try:
        openapi_json = fetch_openapi_json(
            url=args.openapi_url,
            timeout_seconds=args.timeout_seconds,
            retries=args.retries,
            retry_delay_seconds=args.retry_delay_seconds,
        )
        openapi_path, dto_files = generate_dtos(
            openapi_json=openapi_json,
            output_dir=output_dir,
            namespace=args.namespace,
        )
    except Exception as exc:
        print(f"[error] {exc}", file=sys.stderr)
        return 1

    schema_count = len(openapi_json.get("components", {}).get("schemas", {}))
    print(f"[ok] fetched: {args.openapi_url}")
    print(f"[ok] saved OpenAPI: {openapi_path}")
    print(f"[ok] generated DTO files: {len(dto_files)}")
    for dto_file in dto_files:
        print(f"  - {dto_file}")
    print(f"[ok] schema count: {schema_count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
